config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  devise_for :users
  root to: "todolists#index"

  get 'taskdone', to: 'listitems#taskdone', as: :taskdone
  get 'adminshow', to: 'listitems#adminshow', as: :adminshow

  resources :todolists do
    resources :listitems, except:[:index]
    resources :users_todolists, only:[:create]
  end

resources :listitems, only: [:index]


  match 'todolists/:todolist_id/listitems/:id/complete' => 'listitems#complete', as: 'complete_listitem', via: :put

  root "todolists#index"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.status == "admin" } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itemarchive.rb
class Itemarchive < ApplicationRecord
  belongs_to :listitem
end

app/models/listitem.rb
class Listitem < ApplicationRecord
  validates :title, presence: true
  belongs_to :todolist

  include PgSearch::Model
  pg_search_scope :search_by_title,
  against: [ :title],
  using: {
      tsearch: { prefix: true }
    }

  end

app/models/todolist.rb
class Todolist < ApplicationRecord
  validates :title, presence: true
  has_many :listitems, dependent: :destroy
  has_many :users_todolists, dependent: :destroy

  has_many :users_todolists
  has_many :users, through: :users_todolists

  def all_done?
    listitems.all? { |listitem| listitem.status }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :users_todolists, dependent: :destroy
  has_many :todolists, through: :users_todolists
  has_many :listitems, through: :todolists, class_name: 'Listitem', source: :listitems

  def get_items
   self.todolists.map { |todo| todo.listitems }.flatten
 end

end

app/models/users_todolist.rb
class UsersTodolist < ApplicationRecord
  belongs_to :user
  belongs_to :todolist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/listitems_controller.rb
class ListitemsController < ApplicationController

  def index
    @listitems = current_user.get_items
    if params[:query].present?
      @listitems = current_user.listitems.search_by_title(params[:query])
    end
  end

  def new
    @listitem = Listitem.new
    @todolist = Todolist.find(params[:todolist_id])
  end

  def create
    @listitem = Listitem.new(listitem_params)
    @todolist = Todolist.find(params[:todolist_id])
    @listitem.todolist = @todolist
    @listitem.status = false
    if @listitem.save
      redirect_to @todolist
    else
      render :new
    end
  end

  def adminshow
    if current_user.status == "admin"
    @todolists = Todolist.all
    @users = User.all
    else
      redirect_to todolists_path
    end
  end

  def show
    @listitem = Listitem.find(params[:id])
  end

  def taskdone
    @listitems = Listitem.where(status: true)
  end

  def edit
    @listitem = Listitem.find(params[:id])
  end

  def update
    if @listitem.update(listitem_params)
      redirect_to @todolist
    else
      render :edit
    end
  end

  def destroy
    @todolist = Todolist.find(params[:id])
    @listitem = @todolist.listitems.find(params[:todolist_id])
    @listitem.destroy
    redirect_to @todolist
  end

  def complete?
    @todolist = Todolist.find(params[:id])
    @listitem = @todolist.listitems.find(params[:todolist_id])
    return @listitem.status

    # @todolist = Todolist.find(params[:id])
    # @listitem = @todolist.listitems.find(params[:todolist_id])
    # @listitem.update_attribute(:updated_at, Time.now)
    # @itemarchive = Itemarchive.new(title: @listitem.title, status: @listitem.status)
    # @itemarchive.listitem = @listitem
    # if @itemarchive.save
    #   Listitem.find(@listitem.id).destroy
    #   redirect_to @todolist, notice: "Item archivé"
    # else
    #   redirect_to @todolist, notice: "Item non archivé"
    # end

    # redirect_to @todolist, notice: "Item achevé"
  end

  def complete
    @todolist = Todolist.find(params[:id])
    @listitem = @todolist.listitems.find(params[:todolist_id])
    @listitem.status = true
    if @listitem.save
      if @todolist.all_done?
        mail = UserMailer.todoempty(current_user, @todolist)
        mail.deliver_later
        redirect_to todolist_path(@todolist), notice: "Item archivé"
      else
        redirect_to todolist_path(@todolist), notice: "it works"
      end
    else
      redirect_to todolist_path(@todolist), notice: "Item non archivé"
    end
  end


  private

  def listitem_params
    params.require(:listitem).permit(:title, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  def index
    @todolists = current_user.todolists
  end

  def show
    @user_todolist = UsersTodolist.new
  end

  def new
    @todolist = current_user.todolists.build
  end

  def create
    if @todolist = current_user.todolists.create(todolist_params)
      redirect_to @todolist
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todolist.update(todolist_params)
      redirect_to @todolist
    else
      render :edit
    end
  end

  def destroy
    @todolist.destroy
    if @todolists.nil?
      redirect_to todolists_path
    else
      @todolists
    end
  end

  private

  def todolist_params
    params.require(:todolist).permit(:title, :description)
  end

  def set_todolist
    @todolist = current_user.todolists.find(params[:id])
  end
end

app/controllers/users_todolists_controller.rb
class UsersTodolistsController < ApplicationController

  def create
    @users_todolist = UsersTodolist.new
    @user = User.find_by_email(params[:users_todolist][:email])
    @todolist = Todolist.find(params[:todolist_id])
    unless @user.nil?
      @users_todolist.user = @user
      @users_todolist.todolist = @todolist
      @users_todolist.save
      redirect_to todolist_path(@todolist), notice: "L'utilisateur a bien été invité"
    else
      redirect_to todolist_path(@todolist), notice: "L'utilisateur n'existe pas, tester un autre ?"
    end
  end

end

# si l'utilisateur est en base je l'associe à @usertodolist
# sinon renvoyer un message d'erreur

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300&display=swap" rel="stylesheet">
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>

  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/listitems/adminshow.html.erb
 <%# if current_user.status == "admin" %>
    <div class="adminshow">
    <h1>Nom des todo lists</h1>
  <% @todolists.each do |f|%>
    <p><%= f.title %></p>
  <% end %>
  <h1>Nombre de todo lists</h1>
    <p><%= @todolists.count %></p>
  <h1>Nombre d'utilisteurs</h1>
    <p><%= @users.count %></p>
    </div>
<%# else %>
<%# redirect_to todolists_path, notice: "avez pas accès à ces informations" %>
<%# end %>

app/views/listitems/index.html.erb
<div class="listitems">
  <h1>Toutes mes tâches</h1>

  <%= form_tag listitems_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
    placeholder: "Trouver une tâche"
    %>
    <br>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    <ul>
      <% @listitems.each do |f| %>
      <li class="listitems_iteration">
        <%= f.title %>
      </li>
      <% end %>
    </ul>
    <br>

  </div>

app/views/listitems/new.html.erb
<%= simple_form_for [@todolist, @listitem] do |f| %>
  <%= f.input :title %>
  <%= f.submit "Ajouter à la liste", class: "btn btn-primary" %>
<% end %>

app/views/listitems/taskdone.html.erb
<div class="taskdone">

  <h1>Mes tâches effectuées</h1>
  <% @listitems.last(10).each do |f| %>
  <div class="taskdone_iteration">
    <% if f.status == true %>
    <i class="fas fa-check"></i>
    <%= f.title %>  >>
    <%= f.updated_at.localtime.strftime("Tâche effectuée le %d-%m-%Y à %H:%M") %>
    <% end %>
    <% end %>
    <br>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
     <div class="nav-item active">
       <li>
          <%= link_to "Index", todolists_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Tâches terminées", taskdone_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Toutes mes tâches", listitems_path, class: "nav-link" %>
        </li>
        <% if current_user.status == "admin" %>
        <li>
          <%= link_to "Admin", rails_admin_path, class: "nav-link", target: '_blank' %>
        </li>
        <% end %>
        </div>
        <li class="nav-item dropdown">
          <%= image_tag 'sign-out-alt-solid.svg' , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/todolists/edit.html.erb
<%= simple_form_for [@todolist] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Enregistrer les modifications", class: "btn btn-primary" %>
<% end %>

app/views/todolists/index.html.erb
<div class="bloc">

  <div class="todolist_title">
    <h1>Mes Todo lists</h1>
  </div>

  <% @todolists.each do |todo| %>
  <div class="index_row">
    <p><%= link_to todo.title, todolist_path(todo) %></p>
  </div>
  <% end %>

  <div class="create_list">
    <i class="fas fa-plus-square">
      <%= link_to "Créer une nouvelle liste",  new_todolist_path %>
    </i>
  </div>


</div>

app/views/todolists/new.html.erb
<div class=title_create_todo>
<h1>Créer une nouvelle Todo</h1>
</div>
<%= simple_form_for [@todolist] do |f| %>
  <%= f.input :title %>
  <%= f.input :description, label:"Rappel important" %>
  <%= f.submit "Ajouter une todo list", class: "btn btn-primary" %>
<% end %>

app/views/todolists/show.html.erb
<div class="bloc">

  <div class="todolist_title">
    <p><%= @todolist.title%></p>
  </div>

  <div class="todolist_description">
    <h1> Rappels importants !</h1>
    <p><%= @todolist.description %></p>

    <h1> Mes tâches </h1>
  </div>


  <% @todolist.listitems.each do |f| %>
  <div class="flex_todolist">
    <div>
      <% if f.status == false %>
      <%= f.title  %>
    </div>
    <div class="fas fa-check">
      <%= link_to "Tâche terminée",  complete_listitem_path(f), method: :put, data: { confirm: "Etes vous sûr de vouloir sauvegarder cette tâche ?"} %>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <i class="fas fa-plus-square">
    <%= link_to "Ajouter une tâche",  new_todolist_listitem_path(@todolist) %>
  </i><br>
  <i class="fas fa-pen">
    <%= link_to "Modifier la liste",  edit_todolist_path %>
  </i><br>
  <i class="fas fa-trash-alt">
    <%= link_to "Supprimer cette liste",  todolist_path(@todolist), method: :delete, data: { confirm: "Etes vous sûr de vouloir supprimer cette liste ?"} %>
  </i><br>
  <i class="fas fa-hand-point-left">
    <%= link_to "Retour à l'index",  todolists_path %></i><br>

    <i class="far fa-save">
      <%= link_to "Afficher les tâches éffectuées",  taskdone_path %></i><br>


      <%= simple_form_for [@todolist, @user_todolist] do |f| %>
      <!-- [...] -->
      <%= f.input :email, input_html: {value: ""}, label: false, placeholder: "Entrez son mail" %>
      <%= f.submit "Inviter un utilisateur", class: "btn btn-primary" %>
      <!-- [...] -->
      <% end %>
    </div>